Permission.create!([
  {name: "Mostrar Detalles De Un Permiso", description: "Permite mostrar los detalles de un permiso.", action: "show", controller: "Permissions"},
  {name: "Actualizar Permiso", description: "Permite actualizar un permiso. ", action: "update", controller: "Permissions"},
  {name: "Editar Permiso", description: "Permite visualizar la vista editar permiso.", action: "edit", controller: "Permissions"},
  {name: "Generar Semillas", description: "Permite generar las semillas de los permisos y sus relaciones.", action: "generate_seeds", controller: "Permissions"},
  {name: "Obtener Controladores Y Acciones", description: "Permite obtener los controladores y acciones para generar los permisos.", action: "get_controller_actions", controller: "Permissions"},
  {name: "Mostrar Listado De Permisos", description: "Permite mostrar un listado de los permisos.", action: "index", controller: "Permissions"},
  {name: "Nuevo Permiso", description: "Permite visualizar la vista nuevo permiso.", action: "new", controller: "Permissions"},
  {name: "Crear Rol", description: "Permite crear roles.", action: "create", controller: "Roles"},
  {name: "Asignar Permisos A Roles", description: "Permite asignar permisos a un rol existente. ", action: "assign_permissions", controller: "Roles"},
  {name: "Destruir Rol", description: "Permite destruir un rol.", action: "destroy", controller: "Roles"},
  {name: "Editar Rol", description: "Permite visualizar la vista editar rol.", action: "edit", controller: "Roles"},
  {name: "Mostrar Listado De Roles", description: "Permite mostrar un listado de los roles.", action: "index", controller: "Roles"},
  {name: "Nuevo Rol", description: "Permite visualizar la vista nuevo rol.", action: "new", controller: "Roles"},
  {name: "Mostrar Permisos Asignados A Un Rol", description: "Permite mostrar los permisos asignados de un rol.", action: "role_permissions", controller: "Roles"},
  {name: "Mostrar Detalles De Un Rol", description: "Permite mostrar los detalles de un rol.", action: "show", controller: "Roles"},
  {name: "Actualizar Rol", description: "Permite actualizar un rol.", action: "update", controller: "Roles"},
  {name: "Crear Usuario", description: "Permite crear un usuario. ", action: "create_user", controller: "Users::Registrations"},
  {name: "Editar Un Usuario", description: "Permite visualizar la vista editar de un usuario.", action: "edit_user", controller: "Users::Registrations"},
  {name: "Mostrar Listado De Usuarios", description: "Permite mostrar un listado de los usuarios.", action: "index", controller: "Users::Registrations"},
  {name: "Nuevo Usuario", description: "Permite visualizar la vista nuevo usuario.", action: "new_user", controller: "Users::Registrations"},
  {name: "Cambiar Contraseña De Un Usuario", description: "Permite visualizar la vista cambiar contraseña de un usuario.", action: "change_password", controller: "Users::Registrations"},
  {name: "Guardar Contraseña De Un Usuario", description: "Permite guardar la contraseña de un usuario. ", action: "save_password", controller: "Users::Registrations"},
  {name: "Actualizar Usuario", description: "Permite actualizar un usuario.", action: "update_user", controller: "Users::Registrations"},
  {name: "Mostrar Detalles De Un Usuario", description: "Permite mostrar los detalles de un usuario.", action: "show", controller: "Users::Registrations"},
  {name: "Destruir Permiso", description: "Permite destruir un permiso.", action: "destroy", controller: "Permissions"},
  {name: "Eliminar Usuario", description: "Permite destruir un usuario.", action: "destroy", controller: "Users::Registrations"}
])
